/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier Tareas
 */
public class Principal extends javax.swing.JFrame {
    Cafetera c, f2 ,f3;
    int Actual, Max, ActualCafe, MaxCafe, sw;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cmdCrear.setEnabled(true);
        cmdAjustar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdLlenar.setEnabled(false);
        cmdServir.setEnabled(false);
        cmdVaciar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        txtActual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmdCrear = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdAjustar = new javax.swing.JButton();
        cmdLlenar = new javax.swing.JButton();
        cmdVaciar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtActualCafe = new javax.swing.JTextField();
        txtMaxCafe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdServir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cafetera"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cantidad actual");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 20));
        jPanel2.add(txtMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, -1));
        jPanel2.add(txtActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, -1));

        jLabel2.setText("Capacidad Maxima");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 20));

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        cmdAjustar.setText("Ajustar");
        cmdAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAjustarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, -1));

        cmdLlenar.setText("Llenar");
        cmdLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, -1));

        cmdVaciar.setText("Vaciar");
        cmdVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVaciarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Taza de Café"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtActualCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, -1));
        jPanel3.add(txtMaxCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 120, -1));

        jLabel3.setText("Cantidad actual");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 20));

        jLabel4.setText("Capacidad Maxima");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 20));

        cmdServir.setText("Servir");
        cmdServir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdServirActionPerformed(evt);
            }
        });
        jPanel3.add(cmdServir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 270, 220));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cafetera"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado1.setEditable(false);
        txtResultado1.setColumns(20);
        txtResultado1.setRows(5);
        jScrollPane1.setViewportView(txtResultado1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 270, 140));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Taza de Café"));

        txtResultado2.setEditable(false);
        txtResultado2.setColumns(20);
        txtResultado2.setRows(5);
        jScrollPane2.setViewportView(txtResultado2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 270, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        // TODO add your handling code here:
        
        sw = 1;
        
        if (txtActual.getText().trim().isEmpty() && txtMax.getText().trim().isEmpty()){
        c = new Cafetera();
        cmdCrear.setEnabled(true);
        cmdAjustar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLlenar.setEnabled(true);
        cmdServir.setEnabled(true);
        cmdVaciar.setEnabled(true);
        } else {
            try {
                Max = Integer.parseInt(txtMax.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese la capacidad maxima correctamente", "Error", 2);
                txtMax.requestFocusInWindow();
                txtMax.selectAll();
                sw = 0;
            }
            try {
                Actual = Integer.parseInt(txtActual.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese la cantidad actual de la cafetera correctamente", "Error", 2);
                txtActual.requestFocusInWindow();
                txtActual.selectAll();
                sw = 0;
            }
            if (sw == 1){
        Actual = Integer.parseInt(txtActual.getText());
        Max = Integer.parseInt(txtMax.getText());
        c = new Cafetera(Max, Actual);
        cmdCrear.setEnabled(false);
        cmdAjustar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLlenar.setEnabled(true);
        cmdServir.setEnabled(true);
        cmdVaciar.setEnabled(true);
        txtActual.setText("");
        txtMax.setText("");
        JOptionPane.showMessageDialog(this, "Cafetera creada exitosamente", "Informacion", 1);
        }
        }
        
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        // TODO add your handling code here:
        
        txtResultado1.setText("" + c.Mostrar());
        cmdCrear.setEnabled(true);
        cmdAjustar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLlenar.setEnabled(true);
        cmdServir.setEnabled(true);
        cmdVaciar.setEnabled(true);

    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAjustarActionPerformed
        // TODO add your handling code here:
        c.Ajustar(Max);
        cmdCrear.setEnabled(false);
        cmdAjustar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdLlenar.setEnabled(false);
        cmdServir.setEnabled(false);
        cmdVaciar.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Cafetera ajustada exitosamente", "Informacion", 1);
    }//GEN-LAST:event_cmdAjustarActionPerformed

    private void cmdLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarActionPerformed
        // TODO add your handling code here:
        c.Llenar(Actual);
        cmdCrear.setEnabled(false);
        cmdAjustar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdLlenar.setEnabled(false);
        cmdServir.setEnabled(false);
        cmdVaciar.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Cafetera llenada exitosamente", "Informacion", 1);
    }//GEN-LAST:event_cmdLlenarActionPerformed

    private void cmdServirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdServirActionPerformed
        // TODO add your handling code here:
        sw = 1;
        
        if (txtMaxCafe.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la capacidad maxima", "Error", 2);
            txtMaxCafe.requestFocusInWindow();
            sw = 0;
        } else if (txtActualCafe.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la cantidad a servir", "Error", 2);
            txtActualCafe.requestFocusInWindow();
            sw = 0;
        }else {
            try{
                MaxCafe = Integer.parseInt(txtMaxCafe.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese la capacidad maxima correctamente", "Error", 2);
                txtMaxCafe.requestFocusInWindow();
                txtMaxCafe.selectAll();
                sw = 0;
            }
            try {
                ActualCafe = Integer.parseInt(txtActualCafe.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese la cantidad a servir correctamente", "Error", 2);
                txtActualCafe.requestFocusInWindow();
                txtActualCafe.selectAll();
                sw = 0;
            
        }
        if (sw == 1){
        ActualCafe = Integer.parseInt(txtActualCafe.getText());
        MaxCafe = Integer.parseInt(txtMaxCafe.getText());
        
        f2 = new Cafetera(MaxCafe, ActualCafe);
        
        
        f3 = c.ServirTaza(f2);
        txtResultado2.setText("" + f3.Mostrar());
        txtResultado1.setText("" + c.Mostrar());
        txtActualCafe.setText("");
        txtMaxCafe.setText("");
        cmdCrear.setEnabled(false);
        cmdAjustar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdLlenar.setEnabled(true);
        cmdServir.setEnabled(false);
        cmdVaciar.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Taza de café servida exitosamente", "Informacion", 1);
        }
    }//GEN-LAST:event_cmdServirActionPerformed
    }
    private void cmdVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVaciarActionPerformed
        // TODO add your handling code here:
        c.Vaciar(Actual);
        cmdCrear.setEnabled(false);
        cmdAjustar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdLlenar.setEnabled(false);
        cmdServir.setEnabled(false);
        cmdVaciar.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Cafetera vaciada exitosamente", "Informacion", 1);
    }//GEN-LAST:event_cmdVaciarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        // TODO add your handling code here:
        txtActual.setText("");
        txtActualCafe.setText("");
        txtMax.setText("");
        txtMaxCafe.setText("");
        txtResultado1.setText("");
        txtResultado2.setText("");
        txtMax.requestFocusInWindow();
        
        
        
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Niand feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAjustar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLlenar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdServir;
    private javax.swing.JButton cmdVaciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtActual;
    private javax.swing.JTextField txtActualCafe;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMaxCafe;
    private javax.swing.JTextArea txtResultado1;
    private javax.swing.JTextArea txtResultado2;
    // End of variables declaration//GEN-END:variables
}
